### ISSUE TITLE
Missing Button in UI

### ISSUE THREAD

**Issue by FizzBuzz791** [XamarinUniversity/XAM120#1]
## What are you seeing?
No button in the completed exercise one app.

## What is expected?
A button, as was added in step 12.

## What steps did you take to see this?
Opened App.xaml.cs

## Have any logged output/error messages that might help?
N/A

## About your system
N/A

### What operating system are you using? Windows? macOS?
N/A

### What version of Visual Studio are you using?
N/A

**Comment by m08pvv-zz** [comment]
Moreover, if you add a button in the shared App.xaml.cs and try to set a breakpoint, then it will not be able to hit it (if the option 'require source files to exactly match the original version' is switched on) or it will fail to place it in the right place (if that option is switched off)
Visual Studio 15.7.2
Xamarin Forms 3.0.0.482510

Workaround: use Debugger.Break() inside the command for the button.

**Comment by amritav** [comment]
The button is visible in the UI but nothing happens when you click it.
![screenshot_20180607-173513](https://user-images.githubusercontent.com/19224584/41098550-6a259166-6a79-11e8-87c0-48225845ca96.png)

**Comment by patridge** [comment]
Thanks for all the info on this issue. I'll take a look at what's going on and see what needs to be fixed between the code and/or instructions.

**Comment by patridge** [comment]
I am suspecting there might be a configuration issue preventing deployment. I was able to run the current exercise 1 completed solution as well as get a break point to fire in the App constructor where we set the Mainpage. I also did the same with a new app, following the exercise instructions.

If both the UI is inaccurate with the code and your breakpoints are not being hit, you may have an issue with the app not actually deploying the latest from Visual Studio. There may be some information logged in the Output pad that could help diagnose the issue, but you could also try deleting the app explicitly from the device or emulator you are deploying to before trying to debug it again.
